name: clean_architecture_tdd_course
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  internet_connection_checker: ^0.0.1+4
  http: ^0.13.5
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0

flutter:
  uses-material-design: true